"""Initial revision

Revision ID: 9ad631af40d8
Revises: 
Create Date: 2024-09-26 17:06:18.045597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '9ad631af40d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailboxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=60), nullable=False),
    sa.Column('last_history_id', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailbox_id', sa.Integer(), nullable=False),
    sa.Column('messages', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('primary_address', sa.String(length=160), nullable=True),
    sa.Column('financial_institutions', sa.JSON(), nullable=False),
    sa.Column('mailbox_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mailbox_id')
    )
    op.create_table('threads',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('mailbox_id', sa.Integer(), nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('category', sa.Enum('CORRESPONDENCE', 'PROFESSIONAL_OPPORTUNITIES', 'RECEIPTS', 'BILLS_AND_STATEMENTS', 'PROMOTIONS_AND_DEALS', 'NEWSLETTERS', 'UPDATES', 'ORDER_CONFIRMATIONS', 'PRODUCT_RECOMMENDATIONS', 'TICKETS_AND_BOOKINGS', 'COURSES_AND_LEARNING', 'ORGANIZATIONAL_ANNOUNCEMENTS', 'UTILITIES_AND_SERVICES', 'SECURITY_ALERTS', 'SERVICE_NOTIFICATIONS', 'SURVEYS_AND_FEEDBACK', 'POLITICAL', 'SPAM', 'HEALTH_AND_WELLNESS', 'MISCELLANEOUS', name='threadcategory'), nullable=True),
    sa.Column('summary', sa.String(length=80), nullable=True),
    sa.Column('selected_functions', sqlite.JSON(), nullable=False),
    sa.Column('executed_functions', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threads_processed'), 'threads', ['processed'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('mailbox_id', sa.Integer(), nullable=False),
    sa.Column('raw', sa.String(), nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=16), nullable=False),
    sa.Column('label_ids', sqlite.JSON(), nullable=False),
    sa.Column('from_', sa.String(), nullable=False),
    sa.Column('to', sqlite.JSON(), nullable=False),
    sa.Column('cc', sqlite.JSON(), nullable=False),
    sa.Column('bcc', sqlite.JSON(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('body_embedding', sa.BLOB(), nullable=True),
    sa.Column('embedding_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_embedding_generated'), 'messages', ['embedding_generated'], unique=False),

    # Apply the check constraint with batch_alter_table because sqlite doesn't
    # support normal ALTER TABLE statements
    with op.batch_alter_table('messages') as batch_op:
        batch_op.create_check_constraint('chk_body_embedding_valid', "(body_embedding IS NULL) OR (typeof(body_embedding) = 'blob' AND vec_length(body_embedding) = 384)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages') as batch_op:
        batch_op.drop_constraint('chk_body_embedding_valid')
    op.drop_index(op.f('ix_messages_embedding_generated'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_threads_processed'), table_name='threads')
    op.drop_table('threads')
    op.drop_table('profiles')
    op.drop_table('conversations')
    op.drop_table('mailboxes')
    # ### end Alembic commands ###
